version: '3'

services:
  jwt-app:
    build: .
    container_name: jwt-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: always
    volumes:
      - /home/ubuntu/jwt/logs:/app/logs