name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::050752629323:role/MyS3AccessRole
          role-duration-seconds: 1200

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp build/libs/*.jar deployment/
          cp -r scripts deployment/
          cp appspec.yml deployment/
          cp Dockerfile deployment/
          cd deployment && zip -r ../deployment.zip *

      - name: Upload to S3
        run: aws s3 cp deployment.zip s3://areumariawsbucket/cicdtest/deployment.zip

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name Areumari-CICD \
            --deployment-group-name Areumari-CD-group \
            --s3-location bucket=areumariawsbucket,key=cicdtest/deployment.zip,bundleType=zip