name: Deploy to AWS EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Create ZIP deployment package
        run: |
          chmod +x ./scripts/*.sh
          zip -r deploy.zip . -x "*.git*" "*.github*" "*.gitignore"

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://areumari-deploy-bucket/jwt/deploy.zip

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name areumari-app \
            --deployment-group-name areumari-deploy-group \
            --s3-location bucket=areumari-deploy-bucket,key=jwt/deploy.zip,bundleType=zip
